### ISSUE TITLE
Cant make it work

### ISSUE THREAD

**Issue by alefgoto** [pennlabs/django-rest-live#3]
Hi!  I just wanna tell you that there is no way to make it work in my enviroment, i just tried a lot of different things:

This is my requirements.txt:

channels-redis==2.4.2
channels==2.2
daphne
django==3.1.4
django-extensions
django-rest-live
psycopg2
djangorestframework-camel-case

I have set up and followed every step and connected via websockets but i dont receive any update in my model. If you can give a little help or at least upload another example to check with mine it would be great!

Thanks a lot for your work with this package.

Regards

Alejandro

**Comment by davish** [comment]
Hello! Thanks for checking out the package. There should be some logging in the django console when you make subscriptions. Do you see any messages of the form `[REST-LIVE] got subscription to RESOURCE-app.model-*-*`?

**Comment by alefgoto** [comment]
Hi! Thanks for the quick response. Yes, there are some logs in the django console:

System check identified no issues (0 silenced).
December 10, 2020 - 11:56:48
Django version 3.1.4, using settings 'live_consumer_test.settings'
Starting ASGI/Channels version 2.2.0 development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
WebSocket HANDSHAKING /ws/subscribe/ [127.0.0.1:42590]
WebSocket CONNECT /ws/subscribe/ [127.0.0.1:42590]
**[REST-LIVE] got subscription to RESOURCE-live_consumer_app.tarea-id-1**

However, i try to make PATCH via the API endpoint to change values in the instance ID = 1 of the table tarea and nothing happens. I dont receive nothing via websocket (Im using a Google Chrome Client). Also tried to make change via Django Admin in the instance but nothing happen also.

What im sending to connect:

{
  "model": "live_consumer_app.tarea",
  "property": "id",
  "value": 1 
}

Thanks again.

**Comment by davish** [comment]
Could you share your `@subscribable` decorator on your `ModelSerializer`? Did you add any parameters (permissions or a custom `group_key`), or did you just call `@subscribable()`? If you left all of the defaults, then could you try changing the `property` field in the subscription request from `"property": "id"` to `"property": "pk"`? I reviewed the implementation and I believe this is an error in the documentation, but the default property is `pk` in the code. 

Apologies for the misleading docs, will change ASAP! Hope that helps. If not, we can keep debugging.

**Comment by alefgoto** [comment]
It works! 

This is the JSON that i send:

```
{
  "model": "live_consumer_app.Tarea",
  "property": "pk",
  "value": 1 
}
```

You are right, it was the pk value, now im receving updates of that instance.

I have another question, if there is the possibility of subscribe to an entire model and not to an especific instance, so i can receive creations, updates and deletes of al instances.

Thanks a lot for the help

**Comment by davish** [comment]
Glad that it worked! I'll close the issue as resolved.

With regards to your question about subscribing to all model updates, there's no way to do that currently. You can, however, subscribe to all models which are associated with some foreign model following the documentation [here](https://github.com/pennlabs/django-rest-live#subscribe-to-groups). That is a good feature request though, and I'll make sure to keep track of it!
